const presetCoordinates = {
  Jakarta: { latitude: -6.18, longitude: 106.82 },
  Bandung: { latitude: -6.91, longitude: 107.61 },
  Yogyakarta: { latitude: -7.8, longitude: 110.36 },
  Denpasar: { latitude: -8.65, longitude: 115.22 },
};

const weatherCodeMap = {
  0: "Cerah",
  1: "Mayoritas cerah",
  2: "Berawan sebagian",
  3: "Berawan",
  45: "Berkabut",
  48: "Kabut es",
  51: "Gerimis ringan",
  53: "Gerimis",
  55: "Gerimis lebat",
  61: "Hujan ringan",
  63: "Hujan",
  65: "Hujan lebat",
  71: "Salju ringan",
  80: "Hujan lokal",
  81: "Hujan lokal sedang",
  82: "Hujan lokal lebat",
  95: "Badai petir",
  96: "Badai petir dengan hujan es",
  99: "Badai petir kuat",
};

const weatherVisualMap = {
  clear: {
    title: "Langit bersahabat",
    text: "Kondisi terlihat stabil untuk rencana luar ruang.",
  },
  cloudy: {
    title: "Teduh berawan",
    text: "Cocok untuk aktivitas santai, tetap pantau perubahan cuaca.",
  },
  rainy: {
    title: "Ada potensi basah",
    text: "Siapkan payung, jas hujan, atau opsi indoor cadangan.",
  },
  stormy: {
    title: "Cuaca perlu diwaspadai",
    text: "Aktivitas di area terbuka sebaiknya ditunda sampai aman.",
  },
  foggy: {
    title: "Jarak pandang menurun",
    text: "Berhati-hati untuk bersepeda, berkendara, atau aktivitas cepat.",
  },
};

const activities = [
  { name: "Jalan santai", image: "walk", intensity: "light", env: ["urban", "park"], note: "Ringan dan fleksibel untuk area kota atau taman." },
  { name: "Jalan cepat", image: "walk", intensity: "medium", env: ["urban", "park"], note: "Cocok saat udara dan panas masih terkendali." },
  { name: "Jogging", image: "walk", intensity: "medium", env: ["urban", "park"], note: "Butuh AQI dan suhu yang cukup nyaman." },
  { name: "Lari jarak jauh", image: "walk", intensity: "heavy", env: ["urban", "park"], note: "Lebih aman saat AQI baik, UV rendah, dan angin tidak kencang." },
  { name: "Trail running", image: "nature", intensity: "heavy", env: ["nature"], note: "Direkomendasikan hanya untuk area alam, bukit, hutan, atau jalur trail." },
  { name: "Bersepeda santai", image: "bike", intensity: "light", env: ["urban", "park"], note: "Cocok untuk rute pendek dan cuaca stabil." },
  { name: "Road cycling", image: "bike", intensity: "heavy", env: ["urban"], note: "Butuh angin rendah, jalan memadai, dan visibilitas baik." },
  { name: "Mountain biking", image: "nature", intensity: "heavy", env: ["nature"], note: "Lebih cocok untuk area bukit, hutan, atau jalur off-road." },
  { name: "Hiking", image: "nature", intensity: "heavy", env: ["nature"], note: "Tidak disarankan untuk titik kota biasa; perlu area alam atau pegunungan." },
  { name: "Camping", image: "nature", intensity: "medium", env: ["nature"], note: "Cocok jika lokasi berupa area alam dan peluang hujan rendah." },
  { name: "Sepak bola", image: "sport", intensity: "heavy", env: ["urban", "park"], note: "Butuh lapangan terbuka, panas rendah, dan hujan rendah." },
  { name: "Basket outdoor", image: "sport", intensity: "heavy", env: ["urban", "park"], note: "Cocok di area kota/taman saat permukaan lapangan kering." },
  { name: "Voli outdoor", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Butuh angin tidak terlalu kencang." },
  { name: "Badminton outdoor", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Sensitif terhadap angin, lebih cocok saat angin ringan." },
  { name: "Tennis", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Cocok saat UV dan suhu masih aman." },
  { name: "Padel outdoor", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Butuh cuaca kering dan tidak terlalu panas." },
  { name: "Pickleball", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Cocok untuk area lapangan outdoor dengan angin rendah." },
  { name: "Golf", image: "sport", intensity: "light", env: ["park"], note: "Lebih cocok di area lapangan luas dan cuaca stabil." },
  { name: "Yoga outdoor", image: "picnic", intensity: "light", env: ["urban", "park", "nature"], note: "Nyaman saat udara baik dan tidak terlalu panas." },
  { name: "Calisthenics outdoor", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Cocok di taman atau area olahraga luar ruang." },
  { name: "HIIT outdoor", image: "sport", intensity: "heavy", env: ["urban", "park"], note: "Hanya direkomendasikan saat AQI, UV, dan suhu mendukung." },
  { name: "Skateboarding", image: "sport", intensity: "medium", env: ["urban"], note: "Cocok di area kota dengan permukaan kering." },
  { name: "Roller skating", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Butuh permukaan kering dan angin tidak berlebihan." },
  { name: "Stargazing", image: "night", intensity: "light", env: ["nature", "night"], note: "Lebih cocok di area minim cahaya, bukan pusat kota." },
  { name: "Fishing", image: "water", intensity: "light", env: ["water", "nature"], note: "Perlu lokasi dekat air seperti danau, sungai, atau pantai." },
  { name: "Kayaking", image: "water", intensity: "medium", env: ["water"], note: "Direkomendasikan hanya jika lokasi dekat perairan dan angin rendah." },
  { name: "Family outing", image: "picnic", intensity: "light", env: ["urban", "park", "nature"], note: "Cocok untuk aktivitas santai dengan risiko cuaca rendah." },
  { name: "BMX", image: "bike", intensity: "medium", env: ["urban"], note: "Aktivitas sepeda ekstrem BMX di sirkuit atau arena rintangan." },
  { name: "Backpacking", image: "nature", intensity: "heavy", env: ["nature"], note: "Menyusuri alam liar secara mandiri dengan membawa perlengkapan lengkap." },
  { name: "Gravel cycling", image: "bike", intensity: "heavy", env: ["nature", "urban"], note: "Bersepeda melintasi kombinasi jalan aspal dan rute kerikil alam." },
  { name: "Trekking", image: "nature", intensity: "heavy", env: ["nature"], note: "Perjalanan jalan kaki jarak jauh melintasi daerah terpencil atau pegunungan." },
  { name: "Canoeing", image: "water", intensity: "light", env: ["water"], note: "Mendayung kano secara kasual di danau atau perairan yang tenang." },
  { name: "Paddle boarding", image: "water", intensity: "medium", env: ["water"], note: "Berdiri mendayung di atas papan seluncur di perairan tenang." },
  { name: "Rafting", image: "water", intensity: "heavy", env: ["water"], note: "Mengarungi arus jeram sungai yang deras secara beregu." },
  { name: "Rock climbing", image: "nature", intensity: "heavy", env: ["nature"], note: "Memanjat tebing batu alam dengan teknik khusus dan tali pengaman." },
  { name: "Ultimate Frisbee", image: "sport", intensity: "heavy", env: ["urban", "park"], note: "Olahraga lempar tangkap piringan frisbee secara kompetitif dalam tim." },
  { name: "Tai Chi", image: "picnic", intensity: "light", env: ["park", "urban"], note: "Latihan meditasi gerakan lambat untuk kesehatan fisik dan mental." },
  { name: "Stretching outdoor", image: "picnic", intensity: "light", env: ["urban", "park"], note: "Latihan peregangan otot ringan di taman di bawah sinar matahari pagi." },
  { name: "Outdoor bootcamp", image: "sport", intensity: "heavy", env: ["urban", "park"], note: "Latihan kebugaran intensif berkelompok ala militer di area terbuka." },
  { name: "Inline skating", image: "sport", intensity: "medium", env: ["urban", "park"], note: "Meluncur seru menggunakan sepatu roda beroda segaris." },
  { name: "Membaca di taman", image: "picnic", intensity: "light", env: ["park"], note: "Bersantai membaca buku favorit Anda di area rindang taman kota." },
  { name: "Fotografi alam", image: "picnic", intensity: "light", env: ["nature", "water", "park"], note: "Mengambil gambar lanskap alam, flora, dan fauna liar." },
  { name: "Bird watching", image: "nature", intensity: "light", env: ["nature", "park"], note: "Mengamati berbagai jenis burung liar di habitat alaminya." },
  { name: "Bermain layang-layang", image: "picnic", intensity: "light", env: ["park", "water"], note: "Menerbangkan layang-layang di area lapangan terbuka berangin kencang." },
  { name: "Berkebun", image: "picnic", intensity: "light", env: ["nature"], note: "Mengurus tanaman hias atau sayuran di kebun komunitas/pekarangan." },
  { name: "Piknik", image: "picnic", intensity: "light", env: ["park", "nature"], note: "Makan bersama beralaskan tikar piknik di taman berumput hijau." },
  { name: "Sunrise hunting", image: "night", intensity: "medium", env: ["nature", "water"], note: "Mengejar momen indah matahari terbit di dataran tinggi atau pantai." },
  { name: "Sunset hunting", image: "night", intensity: "medium", env: ["nature", "water"], note: "Menikmati pemandangan matahari tenggelam di ufuk barat." }
];
